controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

products_index:
    path: /products
    controller: App\Controller\ProductsController::index

product_edit:
    path: "/product/edit/{id}"
    controller: App\Controller\ProductsController::edit
    methods: ["POST"]

product_list:
    path: /products
    controller: App\Controller\ProductsController::list
    methods: GET

product_delete:
    path: "/product/delete/{id}"
    controller: App\Controller\ProductsController::delete
    methods: DELETE

profile:
    path: /profile
    controller: App\Controller\ProfileController::index
